class url_xpaths:
    username_xpath = '//*[@id="user-name"]'
    password_xpath = '//*[@id="password"]'
    login_button_xpath = '//*[@id="login-button"]'
    left_hanmburger_menu_xpath = '//*[@id="react-burger-menu-btn"]'
    dynamic_cat_xpath = '//*[@id="dynamic_catalog_sidebar_link"]'
    lazy_load_xpath = '//*[@id="dynamic_catalog_lazy_load_link"]'
    spinner_xpath = '//*[@id="dynamic_catalog_spinner_link"]'
    slider_xpath = '//*[@id="dynamic_catalog_slider_link"]'
    items_on_lazy_load_xpath = '//*[@class="dynamic_catalog_card"]'
    item_names_xpath = '(//*[@class="dynamic_catalog_card_name"])[i]'
    all_items_xpath = '//*[@id="inventory_sidebar_link"]'
    bike_light_add_cart_xpath = '//*[@id="add-to-cart-sauce-labs-bike-light"]'
    all_add_to_cart_xpath = '(//*[@class="pricebar"]/button)'
    all_price_xpath = '(//*[@class="pricebar"]/div)'
